# Generated by Django 3.0.6 on 2020-05-30 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_back', '0002_article_comment_goods_order_orderstatus_paymenttype_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
