# Generated by Django 3.0.6 on 2020-05-30 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_back', '0003_auto_20200530_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest_back.Order'),
        ),
    ]
