# Generated by Django 3.0.6 on 2020-05-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_back', '0006_auto_20200530_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='acomplished',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
