# Generated by Django 3.0.6 on 2020-06-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_back', '0007_auto_20200531_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='isGroup',
            field=models.BooleanField(default=False),
        ),
    ]
